import test from 'node:test';
import assert from 'node:assert/strict';
import {Worker as Thread} from 'node:worker_threads';
import {MatchEngine} from '../js/engine.js';
import {normalizeSettings} from '../js/rules.js';
class WebWorker {
  constructor(url){this.worker=new Thread(new URL('./node-worker-bridge.cjs',import.meta.url),{workerData:{url:url.href}});this.worker.on('message',data=>this.onmessage?.({data}));this.worker.on('error',e=>this.onerror?.({message:e.message,preventDefault(){}}));}
  postMessage(data){this.worker.postMessage(data);}terminate(){this.worker.terminate();}
}
globalThis.Worker=WebWorker;
const strategy=(source,faction)=>({id:faction+'/test.py',name:'Test',filename:faction+'/test.py',source,faction});
const constant=move=>`def space_exploration_strategy(h,r,m): return "${move}"`;
const run=(left,right,extra={})=>new MatchEngine().run({left:strategy(left,'f2'),right:strategy(right,'f1'),repeat:1,index:1},normalizeSettings({format:'cross',rounds:10,seed:'runtime-test',...extra}));
test('actual Python runtime: every payoff pair and multiplier',async()=>{for(const [l,r,m,expected]of [['S','S',1,[30,30]],['S','K',1,[10,50]],['K','S',1,[50,10]],['K','K',.5,[10,10]],['K','K',1.5,[30,30]]]){const result=await run(constant(l),constant(r),{multiplier:m});assert.equal(result.status,'complete',result.error);assert.deepEqual([result.rows.at(-1).totalLeft,result.rows.at(-1).totalRight],expected);}});
test('history copies, both perspectives, limited window and true round numbering',async()=>{const source=`def space_exploration_strategy(h,r,m):\n assert len(h)==min(r-1,2)\n assert m==1.25\n for mine,theirs in h: assert mine=="S" and theirs=="K"\n h.clear()\n return "S"`;for(const [a,b]of [[source,constant('K')],[constant('K'),source]]){const result=await run(a,b,{historyLimit:2,multiplier:1.25});assert.equal(result.status,'complete',result.error);}});
test('fresh module state before every match, independent interpreters for twins',async()=>{const source=`n=0\ndef space_exploration_strategy(h,r,m):\n global n\n n+=1\n assert n==r\n return "S" if n==1 else "K"`;const first=await run(source,source),second=await run(source,source);assert.equal(first.status,'complete',first.error);assert.equal(second.status,'complete',second.error);assert.deepEqual(first.rows,second.rows);assert.equal(first.rows[0].left,'S');});
test('Python random repeatability, probabilistic endings, and RNG independence',async()=>{const random=`import random\ndef space_exploration_strategy(h,r,m): return random.choice(["S","K"])`;const a=await run(random,random,{ending:'probability',continuation:95,rounds:100}),b=await run(random,random,{ending:'probability',continuation:95,rounds:100}),c=await run(constant('S'),constant('K'),{ending:'probability',continuation:95,rounds:100});assert.equal(a.status,'complete',a.error);assert.deepEqual(a.rows,b.rows);assert.equal(a.rows.length,c.rows.length);assert.equal((await run(random,random,{ending:'probability',continuation:0})).rows.length,1);assert.equal((await run(random,random,{ending:'probability',continuation:100})).rows.length,10);});
test('syntax, imports and invalid return report the exact file and preserve prefix',async()=>{for(const source of ['x =','import os','def space_exploration_strategy(a): return "S"']){const r=await run(source,constant('S'));assert.equal(r.status,'incomplete');assert.equal(r.rows.length,0);assert.match(r.error,/f2\/test.py/);}const broken=await run('def space_exploration_strategy(h,r,m):\n return "S" if r<4 else "share"',constant('S'));assert.equal(broken.status,'incomplete');assert.equal(broken.rows.length,3);assert.match(broken.error,/round 4/);});
test('timeout and cancellation preserve completed rows and allow recovery',async()=>{const infinite=await run('def space_exploration_strategy(h,r,m):\n while True: pass',constant('S'));assert.equal(infinite.status,'incomplete');assert.match(infinite.error,/timeout/);const e=new MatchEngine(),settings=normalizeSettings({format:'cross',rounds:100});const cancelled=await e.run({left:strategy(constant('S'),'f2'),right:strategy(constant('K'),'f1'),index:1,repeat:1},settings,n=>{if(n===10)e.cancel();});assert.equal(cancelled.status,'cancelled');assert.equal(cancelled.rows.length,10);const recovered=await run(constant('S'),constant('S'));assert.equal(recovered.status,'complete',recovered.error);});
