/* Shared renderer. Edit lecture content in content/week-XX.json.
   Plain text only: JSON never executes HTML or JavaScript. No dependencies. */
(() => {
  'use strict';
  const $=id=>document.getElementById(id),bundle=window.ACCOUNTING_BUNDLE||null;
  const state={course:null,lecture:null,index:0,revealed:false,scale:1,cache:new Map(),route:0};
  const el=(tag,cls='',text)=>{const n=document.createElement(tag);n.className=cls;if(text!==undefined)n.textContent=String(text);return n;};
  const pad=n=>String(n).padStart(2,'0');
  const announce=t=>{$('announcer').textContent=t;};
  function theme(m,target=document.documentElement){for(const [k,v] of Object.entries({accent:m.color,'accent-ink':m.ink,'accent-soft':m.soft,'accent-text':m.onColor}))target.style.setProperty('--'+k,v);}
  function table(b){const wrap=el('div','table-wrap'),t=el('table','data-table'),head=el('thead'),hr=el('tr');b.columns.forEach(c=>{const h=el('th','',c);h.scope='col';hr.append(h);});head.append(hr);t.append(head);const body=el('tbody');b.rows.forEach(r=>{const vals=Array.isArray(r)?r:r.cells,tr=el('tr',Array.isArray(r)?'':r.kind||'');vals.forEach((v,i)=>tr.append(el('td',i>0&&/^[$()\d, .%+−\-]+(?:times|Dr|Cr)?$/.test(String(v))?'numeric':'',v??'')));body.append(tr);});t.append(body);wrap.append(t);if(b.note)wrap.append(el('p','caption',b.note));return wrap;}
  function block(b){
    if(b.type==='text')return el('p','large-text',b.text);
    if(b.type==='bullets'){const n=el('ul','bullets');b.items.forEach(t=>n.append(el('li','',t)));return n;}
    if(b.type==='equation')return el('div','equation',b.text);
    if(b.type==='fraction'){const n=el('div','equation formula');n.append(el('strong','',b.label+' ='));const f=el('span','fraction');f.append(el('span','',b.numerator),el('span','',b.denominator));n.append(f);if(b.suffix)n.append(el('span','',b.suffix));return n;}
    if(b.type==='table')return table(b);
    if(b.type==='splitTables'){const n=el('div','split-tables');b.tables.forEach(t=>n.append(table(t)));return n;}
    if(b.type==='compare'||b.type==='sequence'){const n=el(b.type==='sequence'?'ol':'div',b.type==='sequence'?'sequence':'comparison');n.style.setProperty('--columns',b.items.length);b.items.forEach((item,i)=>{const c=el(b.type==='sequence'?'li':'section');if(b.type==='sequence')c.append(el('span','step-number',pad(i+1)));c.append(el('h2','',item.heading),el('p','',item.text));n.append(c);});return n;}
    if(b.type==='statement'){const n=el('section','statement'),h=el('div','statement-heading');h.append(el('strong','',b.company),el('strong','',b.title),el('span','',b.period));n.append(h,table({columns:['','Amount ($)'],rows:b.rows}));return n;}
    if(b.type==='taccounts'){const n=el('div','taccounts');n.style.setProperty('--columns',b.accounts.length);b.accounts.forEach(a=>{const t=el('section','taccount');t.append(el('h2','',a.name));const sides=el('div','taccount-sides');['debits','credits'].forEach(key=>{const c=el('div');c.append(el('strong','',key==='debits'?'Debit · left':'Credit · right'));a[key].forEach(v=>c.append(el('p','',v)));sides.append(c);});t.append(sides);if(a.balance)t.append(el('p','balance',a.balance));n.append(t);});return n;}
    throw Error('Unknown block type: '+b.type);
  }
  function makeSlide(s,i,revealed=false,printing=false){
    const a=el('article','slide type-'+s.type),h=el('header','slide-header'),ey=el('div','eyebrow');ey.append(el('span','',`Accounting · Week ${pad(state.lecture.week)}`),el('span','',`${pad(i+1)} / ${pad(state.lecture.slides.length)}`));h.append(ey,el('h1','',s.title));if(s.lead)h.append(el('p','lead',s.lead));a.append(h);
    const body=el('div','slide-body');if(revealed)body.append(el('div','reveal-label','Worked answer'));(revealed?s.answer.blocks:s.blocks).forEach(b=>body.append(block(b)));a.append(body);
    const f=el('footer','slide-footer');f.append(el('p','takeaway',(revealed?s.answer.takeaway:null)||s.takeaway||''));if(s.answer&&!printing){const b=el('button','reveal-button',revealed?'Show question':'Reveal answer');b.id='reveal-button';b.setAttribute('aria-expanded',String(revealed));b.addEventListener('click',toggleAnswer);f.append(b);}a.append(f);return a;
  }
  function render(){const s=state.lecture.slides[state.index],a=makeSlide(s,state.index,state.revealed);a.id='slide';a.tabIndex=-1;a.querySelector('h1').id='slide-title';a.setAttribute('aria-labelledby','slide-title');$('slide').replaceWith(a);$('slide-counter').textContent=`${pad(state.index+1)} / ${pad(state.lecture.slides.length)}`;$('previous-button').disabled=state.index===0;$('next-button').disabled=state.index===state.lecture.slides.length-1;$('progress').style.width=`${(state.index+1)/state.lecture.slides.length*100}%`;document.title=`Week ${state.lecture.week} · ${s.title} | Accounting`;$('stage').scrollTop=0;lists();notes();announce(`Week ${state.lecture.week}, slide ${state.index+1}. ${s.title}${state.revealed?'. Answer revealed.':''}`);}
  function lists(){const weeks=$('lecture-list'),slides=$('slide-list');weeks.replaceChildren();slides.replaceChildren();state.course.lectures.forEach(m=>{const li=el('li'),b=el('button',m.id===state.lecture.id?'current':'');const number=el('span','index-number',pad(m.week));number.style.borderColor=m.color;b.append(number,el('span','',m.title));if(m.id===state.lecture.id)b.setAttribute('aria-current','true');b.onclick=()=>{close();navigate(m.id,0);};li.append(b);weeks.append(li);});state.lecture.slides.forEach((s,i)=>{const li=el('li'),b=el('button',i===state.index?'current':'');b.append(el('span','index-number',pad(i+1)),el('span','',s.title));if(i===state.index)b.setAttribute('aria-current','true');b.onclick=()=>{close();navigate(state.lecture.id,i);};li.append(b);slides.append(li);});$('slide-list-title').textContent=`Week ${state.lecture.week} · Slides`;}
  function notes(){const s=state.lecture.slides[state.index],n=$('notes-content');n.replaceChildren();n.append(el('h3','',s.title));if(state.index===0&&state.lecture.goal)n.append(el('p','',`Lecture goal: ${state.lecture.goal}`));const paras=Array.isArray(s.notes)?s.notes:[s.notes];paras.filter(Boolean).forEach(t=>n.append(el('p','',t)));if(s.answer)n.append(el('p','','Ask students to commit to a response before revealing the worked answer. R toggles the answer.'));
    n.append(el('h3','','Sources and context'));const ul=el('ul');[...new Set([...(state.lecture.sources||[]),...(s.sources||[])])].forEach(id=>{const r=state.course.sources[id];if(!r)return;const li=el('li');if(r.url&&/^https?:\/\//.test(r.url)){const a=el('a','',r.title);a.href=r.url;a.target='_blank';a.rel='noopener noreferrer';li.append(a);}else li.append(el('span','',r.title));if(r.detail)li.append(document.createTextNode(' — '+r.detail));ul.append(li);});n.append(ul);$('download-lecture').hidden=Boolean(bundle);$('download-lecture').href=`offline/${state.lecture.id}.html`;$('download-lecture').download=`Accounting-${state.lecture.id}.html`;}
  function close(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
  function open(id){if(state.lecture){close();$(id).showModal();}}
  async function getLecture(id){if(state.cache.has(id))return state.cache.get(id);let d=bundle?.lectures[id];if(!d){const m=state.course.lectures.find(x=>x.id===id),r=await fetch(m.file);if(!r.ok)throw Error('Unable to load '+m.file);d=await r.json();}state.cache.set(id,d);return d;}
  async function route(){const token=++state.route,[want,sid]=decodeURIComponent(location.hash.slice(1)).split('/'),id=state.course.lectures.some(m=>m.id===want)?want:(bundle?.defaultLecture||state.course.lectures[0].id),d=await getLecture(id);if(token!==state.route)return;state.lecture=d;state.index=Math.max(0,d.slides.findIndex(s=>s.id===sid));state.revealed=false;theme(state.course.lectures.find(m=>m.id===id));render();}
  function navigate(id,i){const d=state.cache.get(id)||bundle?.lectures[id],sid=d?.slides[i]?.id,hash=`#${id}${sid?'/'+sid:''}`;if(location.hash===hash){state.index=i;state.revealed=false;render();}else location.hash=hash;}
  function move(n){if(!state.lecture)return;const i=state.index+n;if(i>=0&&i<state.lecture.slides.length)navigate(state.lecture.id,i);}
  function toggleAnswer(){if(!state.lecture?.slides[state.index].answer)return;state.revealed=!state.revealed;render();$('reveal-button').focus({preventScroll:true});}
  function resize(v){state.scale=Math.round(Math.min(1.6,Math.max(.8,v))*100)/100;document.documentElement.style.setProperty('--font-scale',state.scale);$('size-value').textContent=Math.round(state.scale*100)+'%';$('smaller-button').disabled=state.scale<=.8;$('larger-button').disabled=state.scale>=1.6;try{localStorage.setItem('accountingTextScale',String(state.scale));}catch{}announce('Text size '+Math.round(state.scale*100)+' percent');}
  async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{announce('Full screen is unavailable. Use your browser’s full-screen command.');}}
  function print(){if(!state.lecture)return;const n=$('print-content');n.replaceChildren();state.lecture.slides.forEach((s,i)=>{const f=el('div','slide-frame');f.append(makeSlide(s,i,false,true));n.append(f);if(s.answer){const a=el('div','slide-frame');a.append(makeSlide(s,i,true,true));n.append(a);}});}
  function error(e){const n=el('section','error');n.append(el('h1','','The lecture could not load'),el('p','',location.protocol==='file:'?'For offline use, open START-HERE.html or a weekly HTML file from the package.':'Reload the page to try again.'),el('p','',e.message));$('stage').replaceChildren(n);}
  $('lectures-button').onclick=()=>open('lecture-dialog');$('slides-button').onclick=()=>open('slide-dialog');$('notes-button').onclick=()=>open('notes-dialog');$('previous-button').onclick=()=>move(-1);$('next-button').onclick=()=>move(1);$('smaller-button').onclick=()=>resize(state.scale-.1);$('larger-button').onclick=()=>resize(state.scale+.1);$('fit-button').onclick=()=>{resize(1);$('stage').scrollTop=0;};$('fullscreen-button').onclick=fullscreen;$('print-button').onclick=()=>{close();print();window.print();};
  document.querySelector('.skip-link').onclick=e=>{e.preventDefault();$('controls').focus();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
  if(bundle?.handout){const url=URL.createObjectURL(new Blob([bundle.handout],{type:'text/html;charset=utf-8'}));$('case-handout').href=url;}
  document.addEventListener('fullscreenchange',()=>$('fullscreen-button').setAttribute('aria-label',document.fullscreenElement?'Exit full screen':'Enter full screen'));
  document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||document.querySelector('dialog[open]')||e.target.matches('input,textarea,select,[contenteditable=true]'))return;const k=e.key.toLowerCase();if(['arrowright','arrowleft','pagedown','pageup','home','end','r','l','i','n','f','+','=','-'].includes(k))e.preventDefault();if(k==='arrowright'||k==='pagedown')move(1);else if(k==='arrowleft'||k==='pageup')move(-1);else if(k==='r')toggleAnswer();else if(k==='l')open('lecture-dialog');else if(k==='i')open('slide-dialog');else if(k==='n')open('notes-dialog');else if(k==='f')fullscreen();else if(k==='+'||k==='=')resize(state.scale+.1);else if(k==='-')resize(state.scale-.1);else if(k==='home'&&state.lecture)navigate(state.lecture.id,0);else if(k==='end'&&state.lecture)navigate(state.lecture.id,state.lecture.slides.length-1);});
  window.addEventListener('hashchange',()=>route().catch(error));window.addEventListener('beforeprint',print);
  (async()=>{if(bundle)state.course=bundle.course;else{const r=await fetch('course.json');if(!r.ok)throw Error('Unable to load course.json');state.course=await r.json();}try{const n=Number(localStorage.getItem('accountingTextScale'));if(n>=.8&&n<=1.6)resize(n);}catch{}await route();window.ACCOUNTING_READY=true;})().catch(error);
})();
